### PR TITLE
Add @ operator-or-punctuator.

### PR DESCRIPTION
**Pull request by peterhal**
@ is used in the error-control-expression grammar production.

### CODE REVIEW

**Comment by milesj** [comment]
The @ operator is not supported in Hack.

http://docs.hhvm.com/manual/en/hack.unsupported.php

**Comment by peterhal** [comment]
It is included in the expression spec here: https://github.com/hhvm/hack-langspec/blob/master/spec/10-expressions.md#error-control-operator

Should the error-control-operator be removed then?

**Comment by milesj** [comment]
Huh, interesting. Don't have an answer.

**Comment by peterhal** [comment]
Looks like the plan is to add the error-control-operator to the supported list of hack features.

**Pull request merged**
